CFLAGS=-Wall -Wmissing-prototypes  -Wno-sign-compare -g -DHAVE_MMAP

all: xdgmime.o xdgmimeglob.o xdgmimeint.o xdgmimemagic.o xdgmimealias.o xdgmimeparent.o xdgmimecache.o xdgmimeicon.o

clean:
	rm -f *~ *.o
